# Generated by Django 6.0.1 on 2026-04-01 01:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_historicalproduct_product_historicalproductvariant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproductvariant',
            name='stock_quantity',
        ),
        migrations.AlterField(
            model_name='historicalproductvariant',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Variant-specific price. If null, falls back to product base_price.', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Variant-specific price. If null, falls back to product base_price.', max_digits=12, null=True),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('image_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='product_images/')),
                ('alt_text', models.CharField(blank=True, default='', max_length=255)),
                ('is_feature', models.BooleanField(default=False, help_text='Set as the primary image.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product')),
                ('variant', models.ForeignKey(blank=True, help_text='Optional: link image to a specific variant.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.productvariant')),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
