# Generated by Django 6.0.1 on 2026-04-01 02:11

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_historicalproductvariant_stock_quantity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('attribute_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('input_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('select', 'Select (Single)'), ('multiselect', 'Select (Multiple)'), ('boolean', 'Boolean')], default='text', max_length=20)),
                ('unit', models.CharField(blank=True, help_text="e.g., 'GB', 'kg', 'mm'", max_length=20, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_filterable', models.BooleanField(default=True, help_text='Should this appear in the sidebar filters?')),
                ('is_required', models.BooleanField(default=False, help_text='Is this attribute mandatory for its category?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Attribute',
                'verbose_name_plural': 'Attributes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AttributeOption',
            fields=[
                ('option_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=255)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='catalog.attribute')),
            ],
            options={
                'verbose_name': 'Attribute Option',
                'verbose_name_plural': 'Attribute Options',
                'ordering': ['value'],
                'unique_together': {('attribute', 'value')},
            },
        ),
        migrations.CreateModel(
            name='HistoricalAttribute',
            fields=[
                ('attribute_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120)),
                ('input_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('select', 'Select (Single)'), ('multiselect', 'Select (Multiple)'), ('boolean', 'Boolean')], default='text', max_length=20)),
                ('unit', models.CharField(blank=True, help_text="e.g., 'GB', 'kg', 'mm'", max_length=20, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_filterable', models.BooleanField(default=True, help_text='Should this appear in the sidebar filters?')),
                ('is_required', models.BooleanField(default=False, help_text='Is this attribute mandatory for its category?')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Attribute',
                'verbose_name_plural': 'historical Attributes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='CategoryAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_categories', to='catalog.attribute')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_attributes', to='catalog.category')),
            ],
            options={
                'verbose_name': 'Category Attribute',
                'verbose_name_plural': 'Category Attributes',
                'ordering': ['order'],
                'unique_together': {('category', 'attribute')},
            },
        ),
        migrations.CreateModel(
            name='ProductAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.TextField(blank=True, null=True)),
                ('value_number', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('value_boolean', models.BooleanField(blank=True, null=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.attribute')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='catalog.product')),
                ('value_options', models.ManyToManyField(blank=True, to='catalog.attributeoption')),
            ],
            options={
                'verbose_name': 'Product Attribute Value',
                'verbose_name_plural': 'Product Attribute Values',
                'unique_together': {('product', 'attribute')},
            },
        ),
        migrations.CreateModel(
            name='VariantAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.TextField(blank=True, null=True)),
                ('value_number', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('value_boolean', models.BooleanField(blank=True, null=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.attribute')),
                ('value_options', models.ManyToManyField(blank=True, to='catalog.attributeoption')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='catalog.productvariant')),
            ],
            options={
                'verbose_name': 'Variant Attribute Value',
                'verbose_name_plural': 'Variant Attribute Values',
                'unique_together': {('variant', 'attribute')},
            },
        ),
    ]
