# Generated by Django 6.0.1 on 2026-04-09 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_category_image_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproductvariant',
            name='sku',
            field=models.CharField(blank=True, db_index=True, help_text='Stock Keeping Unit — unique identifier for inventory. Auto-generated if not provided.', max_length=100),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='sku',
            field=models.CharField(blank=True, db_index=True, help_text='Stock Keeping Unit — unique identifier for inventory. Auto-generated if not provided.', max_length=100, unique=True),
        ),
    ]
