# Generated by Django 6.0.1 on 2026-04-15 13:04

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_variant_sku_blank'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('discount_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Internal name for the discount, e.g., 'Summer Sale'", max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Optional description for customers.')),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed_amount', 'Fixed Amount')], default='percentage', max_length=20)),
                ('value', models.DecimalField(decimal_places=2, help_text='The value of the discount (e.g., 10 for 10% or $10).', max_digits=12)),
                ('start_date', models.DateTimeField(db_index=True)),
                ('end_date', models.DateTimeField(blank=True, db_index=True, help_text='Optional end date. If blank, discount runs indefinitely.', null=True)),
                ('is_active_override', models.BooleanField(db_index=True, default=True, help_text='Manual kill-switch. Uncheck to stop the discount regardless of dates.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='discounts', to='catalog.category')),
                ('products', models.ManyToManyField(blank=True, related_name='discounts', to='catalog.product')),
                ('variants', models.ManyToManyField(blank=True, related_name='discounts', to='catalog.productvariant')),
            ],
            options={
                'verbose_name': 'Discount',
                'verbose_name_plural': 'Discounts',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalDiscount',
            fields=[
                ('discount_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('name', models.CharField(help_text="Internal name for the discount, e.g., 'Summer Sale'", max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Optional description for customers.')),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed_amount', 'Fixed Amount')], default='percentage', max_length=20)),
                ('value', models.DecimalField(decimal_places=2, help_text='The value of the discount (e.g., 10 for 10% or $10).', max_digits=12)),
                ('start_date', models.DateTimeField(db_index=True)),
                ('end_date', models.DateTimeField(blank=True, db_index=True, help_text='Optional end date. If blank, discount runs indefinitely.', null=True)),
                ('is_active_override', models.BooleanField(db_index=True, default=True, help_text='Manual kill-switch. Uncheck to stop the discount regardless of dates.')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Discount',
                'verbose_name_plural': 'historical Discounts',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
