# Generated by Django 6.0.1 on 2026-04-15 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_discount_historicaldiscount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='is_active_override',
            field=models.BooleanField(db_index=True, default=False, help_text='Manual kill-switch. If true, the discount is stopped regardless of dates.'),
        ),
        migrations.AlterField(
            model_name='historicaldiscount',
            name='is_active_override',
            field=models.BooleanField(db_index=True, default=False, help_text='Manual kill-switch. If true, the discount is stopped regardless of dates.'),
        ),
    ]
