# Generated by Django 6.0.1 on 2026-04-15 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_discount_is_active_override_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproductvariant',
            name='price',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='price',
        ),
        migrations.AddField(
            model_name='historicalproductvariant',
            name='base_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Variant-specific base price. If null, inherits from product base_price.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='base_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Variant-specific base price. If null, inherits from product base_price.', max_digits=12, null=True),
        ),
    ]
