"""
Audit logging utilities for structured application logging.

Provides:
- Thread-local storage for request context (IP, user, resource)
- AuditLogger class for standardized audit log entries
- Integration with Django's logging system

Usage:
    from users.utils.audit import audit_log
    
    audit_log.info(
        action="user.login",
        message="User logged in successfully",
        status="success",
        extra={"method": "email"}
    )
"""
import logging
import threading
from typing import Optional, Any, Dict


# Thread-local storage for request context
_request_context = threading.local()


def set_request_context(
    ip_addr: Optional[str] = None,
    user_id: Optional[str] = None,
    resource: Optional[str] = None
):
    """Set the current request context for logging."""
    _request_context.ip_addr = ip_addr
    _request_context.user_id = str(user_id) if user_id else None
    _request_context.resource = resource


def get_request_context() -> Dict[str, Any]:
    """Get the current request context."""
    return {
        "ip_addr": getattr(_request_context, "ip_addr", None),
        "user_id": getattr(_request_context, "user_id", None),
        "resource": getattr(_request_context, "resource", None),
    }


def clear_request_context():
    """Clear the current request context."""
    _request_context.ip_addr = None
    _request_context.user_id = None
    _request_context.resource = None


class AuditLogger:
    """
    Structured audit logger for application events.
    
    Automatically includes:
    - ip_addr: Client IP address (from request context)
    - user_id: Authenticated user ID (from request context)
    - resource: Request URL path (from request context)
    - timestamp: Auto-generated by formatter
    
    You provide:
    - action: What happened (e.g., "user.login", "user.create")
    - message: Human-readable description
    - status: Result status (e.g., "success", "failed", "error")
    - source: Code location (auto-detected if not provided)
    - extra: Additional context data
    """
    
    def __init__(self, name: str = "audit"):
        self.logger = logging.getLogger(name)
    
    def _log(
        self,
        level: int,
        action: str,
        message: str,
        status: Optional[str] = None,
        source: Optional[str] = None,
        extra: Optional[Dict[str, Any]] = None,
        exc_info: bool = False
    ):
        """Internal logging method with structured fields."""
        context = get_request_context()
        
        # Create log record with extra fields
        extra_fields = {
            "ip_addr": context.get("ip_addr"),
            "user_id": context.get("user_id"),
            "resource": context.get("resource"),
            "action": action,
            "status": status,
            "source": source,
            "extra": extra or {},
        }
        
        self.logger.log(level, message, extra=extra_fields, exc_info=exc_info)
    
    def debug(
        self,
        action: str,
        message: str,
        status: Optional[str] = None,
        source: Optional[str] = None,
        extra: Optional[Dict[str, Any]] = None
    ):
        """Log a debug message."""
        self._log(logging.DEBUG, action, message, status, source, extra)
    
    def info(
        self,
        action: str,
        message: str,
        status: Optional[str] = None,
        source: Optional[str] = None,
        extra: Optional[Dict[str, Any]] = None
    ):
        """Log an info message."""
        self._log(logging.INFO, action, message, status, source, extra)
    
    def warning(
        self,
        action: str,
        message: str,
        status: Optional[str] = None,
        source: Optional[str] = None,
        extra: Optional[Dict[str, Any]] = None
    ):
        """Log a warning message."""
        self._log(logging.WARNING, action, message, status, source, extra)
    
    def error(
        self,
        action: str,
        message: str,
        status: Optional[str] = None,
        source: Optional[str] = None,
        extra: Optional[Dict[str, Any]] = None,
        exc_info: bool = False
    ):
        """Log an error message."""
        self._log(logging.ERROR, action, message, status, source, extra, exc_info)
    
    def critical(
        self,
        action: str,
        message: str,
        status: Optional[str] = None,
        source: Optional[str] = None,
        extra: Optional[Dict[str, Any]] = None,
        exc_info: bool = False
    ):
        """Log a critical message."""
        self._log(logging.CRITICAL, action, message, status, source, extra, exc_info)


# Global audit logger instance
audit_log = AuditLogger("audit")
