# Generated by Django 6.0.1 on 2026-01-26 01:18

import users.managers
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedLoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(db_index=True, max_length=45, unique=True)),
                ('failed_attempts', models.PositiveIntegerField(db_index=True, default=0)),
                ('locked_until', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_attempt_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-last_attempt_at'],
                'indexes': [models.Index(fields=['ip_address'], name='users_faile_ip_addr_8829d0_idx'), models.Index(fields=['locked_until'], name='users_faile_locked__11a14d_idx'), models.Index(fields=['last_attempt_at'], name='users_faile_last_at_a70e21_idx')],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=75)),
                ('last_name', models.CharField(max_length=75)),
                ('telephone_number', models.CharField(blank=True, db_index=True, max_length=32, null=True, unique=True)),
                ('email_verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified')], db_index=True, default='pending', max_length=16)),
                ('telephone_verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('no_number', 'No number')], db_index=True, default='no_number', max_length=16)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_staff', models.BooleanField(db_index=True, default=False)),
                ('is_superuser', models.BooleanField(db_index=True, default=False)),
                ('is_soft_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('locale', models.CharField(blank=True, max_length=10, null=True)),
                ('password_changed_at', models.DateTimeField(blank=True, null=True)),
                ('password_expires_in_days', models.PositiveIntegerField(default=90)),
                ('session_version', models.IntegerField(default=0)),
                ('failed_login_attempts', models.PositiveIntegerField(db_index=True, default=0)),
                ('locked_until', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_soft_deleted', False)), fields=('telephone_number',), name='unique_active_telephone_number')],
            },
            managers=[
                ('objects', users.managers.UserManager()),
            ],
        ),
    ]
