# Generated by Django 6.0.1 on 2026-02-16 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at'], 'permissions': [('can_soft_delete', 'Can soft delete a user'), ('can_deactivate', 'Can deactivate a user'), ('can_activate', 'Can activate a user')]},
        ),
    ]
