# Generated by Django 6.0.1 on 2026-02-16 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at'], 'permissions': [('can_soft_delete_user', 'Can soft delete a user'), ('can_deactivate_user', 'Can deactivate a user'), ('can_activate_user', 'Can activate a user')]},
        ),
    ]
