# Generated by Django 6.0.1 on 2026-04-01 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telephone_number',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
    ]
